credentials:
  usernames:
    jsmith:
      email: yonas.mersha14@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Yonas Mersha
      password: abc # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - yonas.mersha14@gmail.com
